name = "Amethyst Smp"
author = "jvdsat"
version = "1.0.0"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "d6ec5f327133db0bcb574973745c3d3152a581ce92b6cb7d6f24eab78a3ac22e"

[versions]
minecraft = "1.21.1"
neoforge = "21.1.234"
