name = "Amethyst Smp"
author = "jvdsat"
version = "1.0.0"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "94f55d616908e42918457d63a81c6ac90e2cb1f72ed6df814b4dfa2fd82aa295"

[versions]
minecraft = "1.21.1"
neoforge = "21.1.234"
