name = "Amethyst Smp"
author = "jvdsat"
version = "1.0.0"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "f28c2aa89e45f1aecf3498dee4e5e307b03fd8ceae886cd01b8a4d9be764e7d7"

[versions]
minecraft = "1.21.1"
neoforge = "21.1.234"
